name: CI
on:
  push:
    branches:
      - main
jobs:
  failing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: node -e "process.exit(1)"

  test:
    runs-on: ubuntu-latest
    needs: failing-job
    if: ${{ failure() }}
    steps:
      - name: Test output of previous job
        run: echo ${{ needs.failing-job.result }}
